---
- name: Install Docker on CentOS
  hosts: Client1
  become: true
  tasks:
    - name: Add Docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
 
    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
 
    - name: Start Docker service
      systemd:
        name: docker
        state: started
 
    - name: Enable Docker service
      systemd:
        name: docker
        enabled: true
 
    - name: Check Docker service status
      command: systemctl status docker
      register: docker_status
      ignore_errors: yes
 
    - name: Print Docker service status
      debug:
        var: docker_status.stdout_lines
    - name: Install Maven
      dnf:
        name: maven
        state: present
