version: '3.8'

services:
  banking-microservice:
    image: banking-microservice:latest
    build:
      context: .  # Build from the current directory
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 on the host
    networks:
      - banking-network
    volumes:
      - ./target/banking-microservice-1.0-SNAPSHOT.jar:/app/app.jar

networks:
  banking-network:
    driver: bridge
