---
- name: Install Docker, Docker Compose, and Maven on Rocky Linux 9
  hosts: Client1
  become: yes
  tasks:
  
    # Install required dependencies
    - name: Install dependencies for Docker
      dnf:
        name:
          - curl
          - gnupg
          - lsb-release
        state: present
    
    # Add Docker repository and install Docker Engine
    - name: Add Docker repository
      command: curl -fsSL https://get.docker.com | bash
    
    - name: Install Docker
      dnf:
        name: docker
        state: present

    # Enable and start Docker service
    - name: Enable Docker service to start on boot
      systemd:
        name: docker
        enabled: yes
        state: started
    
    # Install Docker Compose
    - name: Download Docker Compose binary
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Verify Docker Compose installation
      command: docker-compose --version

    # Install Maven
    - name: Install Maven
      dnf:
        name: maven
        state: present

    # Verify Maven installation
    - name: Verify Maven installation
      command: mvn -v
