---
- name: Install Docker, Docker Compose, and Maven on Rocky Linux 9
  hosts: Client1  # Ensure this matches your inventory group
  become: yes
  tasks:
    - name: Install dependencies for Docker and Maven
      dnf:
        name:
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Enable EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Set up Docker repository for CentOS/RHEL
      copy:
        content: |
          [docker-ce-stable]
          name=Docker CE Stable - $basearch
          baseurl=https://download.docker.com/linux/centos/7/x86_64/stable
          enabled=1
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      dnf:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Install Maven
      dnf:
        name: maven
        state: present

    - name: Verify Maven installation
      command: mvn -v
