---
- name: Install Docker, Docker Compose, and Maven on Rocky Linux 9
  hosts: Client1  # Ensure this matches your inventory group
  become: yes
  tasks:
    - name: Install dependencies for Docker
      dnf:
        name:
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Set up Docker repository
      dnf:
        name: "https://download.docker.com/linux/centos/docker-ce.repo"
        state: present

    - name: Install Docker
      dnf:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Install Maven
      dnf:
        name: maven
        state: present

    - name: Verify Maven installation
      command: mvn -v
